<div class="container col-md-10 col-sm-12 col-lg-9 d-flex justify-content-between gap-3">
<div class="col-md-8 col-sm-12" style="max-width:93vw">
<?= showError('post_img') ?>
<?php if (!$posts): ?><p class="p-2 bg-white border rounded text-center my-3">Theo dõi ai đó hoặc thêm bài viết mới</p><?php endif; ?>
<?php foreach ($posts as $post): $comments=getComments($post['id'], 3, 0); ?>
<div class="card mt-4">
    <div class="card-title d-flex justify-content-between align-items-center p-2 mb-0"><div><img src="public/images/profile/<?= e($post['profile_pic']) ?>" height="30" width="30" class="rounded-circle border me-2" alt=""><a href="?u=<?= rawurlencode($post['username']) ?>" class="text-decoration-none text-dark"><?= e($post['first_name'].' '.$post['last_name']) ?></a></div><div class="dropdown"><button class="btn" data-bs-toggle="dropdown"><i class="bi bi-three-dots-vertical"></i></button><ul class="dropdown-menu dropdown-menu-end"><?php if ((int)$post['uid']===(int)$user['id']): ?><li><form method="post" action="?action=delete_post" onsubmit="return confirm('Xóa bài viết này?')"><?= csrfField() ?><input type="hidden" name="post_id" value="<?= (int)$post['id'] ?>"><button class="dropdown-item" type="submit"><i class="bi bi-trash-fill"></i> Xóa bài viết</button></form></li><li><a class="dropdown-item" href="#" data-bs-toggle="modal" data-bs-target="#editPost<?= (int)$post['id'] ?>"><i class="bi bi-pencil-fill"></i> Chỉnh sửa</a></li><?php endif; ?><li><a class="dropdown-item" href="#" onclick="reportPost(<?= (int)$post['id'] ?>);return false"><i class="bi bi-flag-fill"></i> Báo cáo vi phạm</a></li></ul></div></div>
    <?php if ($post['post_text'] !== ''): ?><div class="card-body py-2"><?= nl2br(e($post['post_text'])) ?></div><?php endif; ?>
    <img src="public/images/posts/<?= e($post['post_img']) ?>" loading="lazy" class="post-image" alt="Bài đăng">
    <div class="p-2 border-bottom d-flex align-items-center gap-3"><span><i class="bi bi-heart like_btn" style="display:<?= !empty($post['liked_by_me'])?'none':'' ?>" data-post-id="<?= (int)$post['id'] ?>"></i><i class="bi bi-heart-fill unlike_btn text-danger" style="display:<?= !empty($post['liked_by_me'])?'':'none' ?>" data-post-id="<?= (int)$post['id'] ?>"></i></span><span><i class="bi bi-chat-left"></i> <?= (int)$post['comment_count'] ?> Bình luận</span></div>
    <div class="px-2 pt-2"><span id="likecount<?= (int)$post['id'] ?>"><?= (int)$post['like_count'] ?></span> Thích <span class="small text-muted ms-2">Đã đăng <?= e(show_time($post['created_at'])) ?></span></div>
    <div class="p-2" id="comment-section<?= (int)$post['id'] ?>"><?php if (!$comments): ?><p class="text-muted nce">Chưa có bình luận nào.</p><?php endif; ?><?php foreach ($comments as $comment): ?><div class="d-flex align-items-start border-bottom py-2"><img src="public/images/profile/<?= e($comment['profile_pic']) ?>" width="36" height="36" class="rounded-circle me-2" alt=""><div class="flex-grow-1"><strong><a href="?u=<?= rawurlencode($comment['username']) ?>" class="text-decoration-none text-dark">@<?= e($comment['username']) ?></a></strong> <?= e($comment['comment']) ?><div class="small text-muted"><?= e(show_time($comment['created_at'])) ?></div></div><?php if ((int)$comment['user_id']===(int)$user['id']): ?><form method="post" action="?action=delete_comment" class="ms-2"><?= csrfField() ?><input type="hidden" name="comment_id" value="<?= (int)$comment['id'] ?>"><button class="btn btn-link text-danger small p-0" type="submit">Xóa</button></form><?php endif; ?></div><?php endforeach; ?></div>
    <div class="input-group p-2 border-top"><input type="text" maxlength="2000" class="form-control border-0 comment-input" placeholder="Bình luận đi..."><button class="btn btn-outline-primary border-0 add-comment" data-page="wall" data-cs="comment-section<?= (int)$post['id'] ?>" data-post-id="<?= (int)$post['id'] ?>"><i class="bi bi-send"></i></button></div>
</div>
<?php if ((int)$post['uid']===(int)$user['id']): ?><div class="modal fade" id="editPost<?= (int)$post['id'] ?>"><div class="modal-dialog"><form class="modal-content" action="?action=update_post" method="post"><?= csrfField() ?><div class="modal-header"><h5 class="modal-title">Chỉnh sửa bài viết</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><input type="hidden" name="post_id" value="<?= (int)$post['id'] ?>"><textarea name="post_content" maxlength="10000" class="form-control" rows="4"><?= e($post['post_text']) ?></textarea></div><div class="modal-footer"><button class="btn btn-primary">Cập nhật</button></div></form></div></div><?php endif; ?>
<?php endforeach; ?>
</div>
<div class="col-lg-4 d-none d-lg-block mt-4 p-3"><div class="d-flex align-items-center p-2"><img src="public/images/profile/<?= e($user['profile_pic']) ?>" height="60" width="60" class="rounded-circle border me-2" alt=""><div><a href="?u=<?= rawurlencode($user['username']) ?>" class="text-decoration-none text-dark fw-bold"><?= e($user['first_name'].' '.$user['last_name']) ?></a><p class="mb-0 text-muted">@<?= e($user['username']) ?></p></div></div><h6 class="text-muted p-2">Bạn có thể theo dõi họ!</h6><?php foreach ($followSuggestions as $suggestion): ?><div class="d-flex justify-content-between align-items-center p-2"><div class="d-flex align-items-center"><img src="public/images/profile/<?= e($suggestion['profile_pic']) ?>" height="40" width="40" class="rounded-circle border me-2" alt=""><a href="?u=<?= rawurlencode($suggestion['username']) ?>" class="text-decoration-none text-dark">@<?= e($suggestion['username']) ?></a></div><button class="btn btn-sm btn-primary followbtn" data-user-id="<?= (int)$suggestion['id'] ?>">Theo dõi</button></div><?php endforeach; if(!$followSuggestions): ?><p class="text-muted">Không có gợi ý nào.</p><?php endif; ?></div>
</div>
<script>
function reportPost(postId){if(!confirm('Bạn có chắc muốn báo cáo bài viết này không?'))return;const body=new URLSearchParams({post_id:String(postId)});window.handbookFetch('?action=report_post',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:body.toString()}).then(async r=>{const data=await r.json();alert(data.message||'Đã xử lý yêu cầu.');}).catch(()=>alert('Không thể báo cáo bài viết.'));}
</script>
