<div class="container col-md-9 col-sm-11">
    <div class="rounded p-4 mt-4 d-md-flex gap-5">
        <div class="col-md-4 d-flex justify-content-center"><img src="public/images/profile/<?= e($profile['profile_pic']) ?>" class="img-thumbnail rounded-circle mb-3" style="width:170px;height:170px;object-fit:cover"></div>
        <div class="col-md-8"><div class="d-flex align-items-center gap-3"><span style="font-size:xx-large"><?= e($profile['first_name'] . ' ' . $profile['last_name']) ?></span><?php if ((int)$user['id'] !== (int)$profile['id'] && !checkBS($profile['id'])): ?><div class="dropdown"><button class="btn" data-bs-toggle="dropdown"><i class="bi bi-three-dots"></i></button><ul class="dropdown-menu"><li><a class="dropdown-item" href="#" data-bs-toggle="modal" data-bs-target="#chatbox" onclick="popchat(<?= (int)$profile['id'] ?>)"><i class="bi bi-chat-fill"></i> Nhắn tin</a></li><li><a class="dropdown-item" href="?action=block_user&id=<?= (int)$profile['id'] ?>&username=<?= rawurlencode($profile['username']) ?>"><i class="bi bi-x-circle-fill"></i> Chặn</a></li></ul></div><?php endif; ?></div>
        <span class="text-secondary">@<?= e($profile['username']) ?></span>
        <?php if (!checkBS($profile['id'])): ?><div class="d-flex gap-2 my-3"><span class="btn btn-sm btn-primary disabled"><?= count($profilePosts) ?> bài đăng</span><span class="btn btn-sm btn-primary disabled"><?= count($profile['followers']) ?> người theo dõi</span><span class="btn btn-sm btn-primary disabled"><?= count($profile['following']) ?> đang theo dõi</span></div><?php endif; ?>
        <?php if ((int)$user['id'] !== (int)$profile['id']): ?><div class="my-2"><?php if (checkBlockStatus($user['id'], $profile['id'])): ?><button class="btn btn-danger unblockbtn" data-user-id="<?= (int)$profile['id'] ?>">Mở chặn</button><?php elseif (checkBlockStatus($profile['id'], $user['id'])): ?><div class="alert alert-danger">@<?= e($profile['username']) ?> đã chặn bạn!</div><?php elseif (checkFollowStatus($profile['id'])): ?><button class="btn btn-danger unfollowbtn" data-user-id="<?= (int)$profile['id'] ?>">Bỏ theo dõi</button><?php else: ?><button class="btn btn-primary followbtn" data-user-id="<?= (int)$profile['id'] ?>">Theo dõi</button><?php endif; ?></div><?php endif; ?>
        </div>
    </div>
    <h3 class="border-bottom">Bài đăng</h3>
    <?php if (checkBS($profile['id'])): ?><div class="alert alert-secondary text-center">Bạn không được phép xem bài viết!</div><?php elseif (!$profilePosts): ?><p class="p-2 bg-white border rounded text-center my-3">Người dùng chưa có bài viết nào</p><?php else: ?>
    <div class="gallery d-flex flex-wrap gap-2 mb-4"><?php foreach ($profilePosts as $post): $likes=getLikes($post['id']); $comments=getComments($post['id']); ?><img src="public/images/posts/<?= e($post['post_img']) ?>" data-bs-toggle="modal" data-bs-target="#profilePost<?= (int)$post['id'] ?>" width="300" height="300" style="object-fit:cover" class="rounded">
    <div class="modal fade" id="profilePost<?= (int)$post['id'] ?>" tabindex="-1"><div class="modal-dialog modal-xl modal-dialog-centered"><div class="modal-content"><div class="modal-body d-md-flex p-0"><div class="col-md-8"><img src="public/images/posts/<?= e($post['post_img']) ?>" class="w-100" style="max-height:90vh;object-fit:contain"></div><div class="col-md-4 p-3"><h5><?= e($profile['first_name'].' '.$profile['last_name']) ?></h5><p><?= e($post['post_text']) ?></p><div class="small text-muted mb-3"><?= count($likes) ?> Thích · <?= count($comments) ?> Bình luận</div><div id="profile-comments-<?= (int)$post['id'] ?>"><?php foreach ($comments as $comment): $cuser=getUser($comment['user_id']); if(!$cuser) continue; ?><div class="border-bottom py-2"><strong>@<?= e($cuser['username']) ?></strong> <?= e($comment['comment']) ?><div class="small text-muted"><?= e(show_time($comment['created_at'])) ?></div></div><?php endforeach; ?></div><?php if (checkFollowStatus($profile['id']) || (int)$profile['id']===(int)$user['id']): ?><div class="input-group mt-2"><input class="form-control comment-input" placeholder="Bình luận..."><button class="btn btn-outline-primary add-comment" data-cs="profile-comments-<?= (int)$post['id'] ?>" data-post-id="<?= (int)$post['id'] ?>">Đăng</button></div><?php endif; ?></div></div></div></div></div>
    <?php endforeach; ?></div><?php endif; ?>
</div>
